server:
  port: 8761

spring:
  application:
    name: discovery_service
  cloud:
    config:
      uri: http://config-service:8888
      name: ecommerce

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false